

export const trainList = [
  {
    trainNo: "16534",
    trainName: "KSR Bengaluru - Jodhpur Express",
    status: "Originating",
    arrival: "--",
    departure: "00:05",
  },
  {
    trainNo: "11302",
    trainName: "KSR Bengaluru - Mumbai Udyan Express",
    status: "Originating",
    arrival: "--",
    departure: "00:30",
  },
  {
    trainNo: "06269",
    trainName: "Bangarapet - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "00:40",
    departure: "--",
  },
  {
    trainNo: "16218",
    trainName: "Sainagar Shirdi - Mysuru Express",
    status: "Passing Through",
    arrival: "00:50",
    departure: "00:55",
  },
  {
    trainNo: "22817",
    trainName: "Howrah - Mysuru SF Express",
    status: "Passing Through",
    arrival: "00:50",
    departure: "00:55",
  },
  {
    trainNo: "16531",
    trainName: "Ajmer - KSR Bengaluru Garib Nawaz",
    status: "Terminating",
    arrival: "02:30",
    departure: "--",
  },
  {
    trainNo: "16533",
    trainName: "Jodhpur - KSR Bengaluru Express",
    status: "Terminating",
    arrival: "02:30",
    departure: "--",
  },
  {
    trainNo: "16507",
    trainName: "Jodhpur - KSR Bengaluru Express",
    status: "Terminating",
    arrival: "02:30",
    departure: "--",
  },
  {
    trainNo: "16021",
    trainName: "Mysuru - MGR Chennai Kaveri Express",
    status: "Passing Through",
    arrival: "03:45",
    departure: "03:50",
  },
  {
    trainNo: "17392",
    trainName: "Sindhanur - KSR Bengaluru Express",
    status: "Terminating",
    arrival: "03:55",
    departure: "--",
  },
  {
    trainNo: "06522",
    trainName: "Hindupur - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "04:00",
    departure: "--",
  },
  {
    trainNo: "56263",
    trainName: "Mysuru - KSR Bengaluru Passenger",
    status: "Terminating",
    arrival: "04:15",
    departure: "--",
  },
  {
    trainNo: "16220",
    trainName: "Tirupati - Chamarajanagar Express",
    status: "Passing Through",
    arrival: "04:25",
    departure: "04:35",
  },
  {
    trainNo: "12657",
    trainName: "MGR Chennai - KSR Bengaluru Mail",
    status: "Terminating",
    arrival: "04:35",
    departure: "--",
  },
  {
    trainNo: "16594",
    trainName: "Nanded - KSR Bengaluru Express",
    status: "Terminating",
    arrival: "04:50",
    departure: "--",
  },
  {
    trainNo: "16228",
    trainName: "Talguppa - Mysuru Express",
    status: "Passing Through",
    arrival: "04:50",
    departure: "05:00",
  },
  {
    trainNo: "56912",
    trainName: "Hubballi - KSR Bengaluru Passenger",
    status: "Terminating",
    arrival: "05:15",
    departure: "--",
  },
  {
    trainNo: "22692",
    trainName: "NZM - KSR Bengaluru Rajdhani",
    status: "Terminating",
    arrival: "05:20",
    departure: "--",
  },
  {
    trainNo: "20661",
    trainName: "KSR Bengaluru - Dharwad Vande Bharat",
    status: "Originating",
    arrival: "--",
    departure: "05:45",
  },
  {
    trainNo: "16231",
    trainName: "Mayiladuthurai - Mysuru Express",
    status: "Passing Through",
    arrival: "05:40",
    departure: "05:45",
  },
  {
    trainNo: "16591",
    trainName: "SSS Hubballi - Mysuru Hampi Exp",
    status: "Passing Through",
    arrival: "05:50",
    departure: "06:00",
  },
  {
    trainNo: "12028",
    trainName: "KSR Bengaluru - MGR Chennai Shatabdi",
    status: "Originating",
    arrival: "--",
    departure: "06:00",
  },
  {
    trainNo: "11301",
    trainName: "Mumbai - KSR Bengaluru Udyan Exp",
    status: "Terminating",
    arrival: "06:00",
    departure: "--",
  },
  {
    trainNo: "16590",
    trainName: "Rani Chennamma Express",
    status: "Terminating",
    arrival: "06:15",
    departure: "--",
  },
  {
    trainNo: "12608",
    trainName: "KSR Bengaluru - MGR Chennai Lalbagh",
    status: "Originating",
    arrival: "--",
    departure: "06:20",
  },
  {
    trainNo: "12785",
    trainName: "Kacheguda - Mysuru SF Express",
    status: "Passing Through",
    arrival: "06:20",
    departure: "06:25",
  },
  {
    trainNo: "06388",
    trainName: "Kolar - KSR Bengaluru DEMU",
    status: "Terminating",
    arrival: "06:25",
    departure: "--",
  },
  {
    trainNo: "16525",
    trainName: "Kanyakumari - KSR Bengaluru Island",
    status: "Terminating",
    arrival: "06:40",
    departure: "--",
  },
  {
    trainNo: "16512",
    trainName: "Kannur - KSR Bengaluru Express",
    status: "Terminating",
    arrival: "06:50",
    departure: "--",
  },
  {
    trainNo: "16235",
    trainName: "Tuticorin - Mysuru Express",
    status: "Passing Through",
    arrival: "06:55",
    departure: "07:00",
  },
  {
    trainNo: "06596",
    trainName: "Marikuppam - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "08:20",
    departure: "--",
  },
  {
    trainNo: "66553",
    trainName: "Tumakuru - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "08:30",
    departure: "--",
  },
  {
    trainNo: "16316",
    trainName: "Kochuveli - Mysuru Express",
    status: "Passing Through",
    arrival: "08:30",
    departure: "08:50",
  },
  {
    trainNo: "01777",
    trainName: "Marikuppam - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "08:45",
    departure: "--",
  },
  {
    trainNo: "17236",
    trainName: "Nagercoil - KSR Bengaluru Express",
    status: "Terminating",
    arrival: "09:05",
    departure: "--",
  },
  {
    trainNo: "01763",
    trainName: "Marikuppam - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "09:20",
    departure: "--",
  },
  {
    trainNo: "66547",
    trainName: "Bangarapet - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "09:30",
    departure: "--",
  },
  {
    trainNo: "16215",
    trainName: "Mysuru - KSR Bengaluru Chamundi",
    status: "Terminating",
    arrival: "09:35",
    departure: "--",
  },
  {
    trainNo: "01775",
    trainName: "Marikuppam - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "10:10",
    departure: "--",
  },
  {
    trainNo: "12007",
    trainName: "Chennai - Mysuru Shatabdi Express",
    status: "Passing Through",
    arrival: "10:45",
    departure: "10:50",
  },
  {
    trainNo: "17308",
    trainName: "Bagalkot - Mysuru Basava Express",
    status: "Passing Through",
    arrival: "11:15",
    departure: "11:30",
  },
  {
    trainNo: "20660",
    trainName: "KSR Bengaluru - Mysuru Rajya Rani SF",
    status: "Originating",
    arrival: "--",
    departure: "11:30",
  },
  {
    trainNo: "01780",
    trainName: "Marikuppam - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "11:55",
    departure: "--",
  },
  {
    trainNo: "06592",
    trainName: "Mysuru - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "12:20",
    departure: "--",
  },
  {
    trainNo: "12725",
    trainName: "KSR Bengaluru - Dharwad Siddhaganga",
    status: "Originating",
    arrival: "--",
    departure: "12:45",
  },
  {
    trainNo: "12975",
    trainName: "Mysuru - Jaipur SF Express",
    status: "Passing Through",
    arrival: "12:50",
    departure: "13:15",
  },
  {
    trainNo: "22625",
    trainName: "Chennai - KSR Bengaluru Double Decker",
    status: "Terminating",
    arrival: "13:10",
    departure: "--",
  },
  {
    trainNo: "12726",
    trainName: "Dharwad - KSR Bengaluru Siddhaganga",
    status: "Terminating",
    arrival: "13:50",
    departure: "--",
  },
  {
    trainNo: "12613",
    trainName: "Mysuru - KSR Bengaluru Wodeyar SF",
    status: "Terminating",
    arrival: "14:00",
    departure: "--",
  },
  {
    trainNo: "12639",
    trainName: "Chennai - KSR Bengaluru Brindavan",
    status: "Terminating",
    arrival: "14:00",
    departure: "--",
  },
  {
    trainNo: "22626",
    trainName: "KSR Bengaluru - MGR Chennai DD",
    status: "Originating",
    arrival: "--",
    departure: "14:30",
  },
  {
    trainNo: "20608",
    trainName: "Mysuru - Chennai Vande Bharat",
    status: "Passing Through",
    arrival: "14:45",
    departure: "14:50",
  },
  {
    trainNo: "12640",
    trainName: "KSR Bengaluru - MGR Chennai Brindavan",
    status: "Originating",
    arrival: "--",
    departure: "15:10",
  },
  {
    trainNo: "11014",
    trainName: "Coimbatore - Mumbai LTT Express",
    status: "Passing Through",
    arrival: "15:45",
    departure: "16:00",
  },
  {
    trainNo: "12008",
    trainName: "Mysuru - Chennai Shatabdi Express",
    status: "Passing Through",
    arrival: "16:10",
    departure: "16:15",
  },
  {
    trainNo: "20659",
    trainName: "KSR Bengaluru - Mysuru Rajya Rani",
    status: "Terminating",
    arrival: "17:20",
    departure: "--",
  },
  {
    trainNo: "17325",
    trainName: "Hubballi - Ashokapuram Vishwamanava",
    status: "Passing Through",
    arrival: "17:30",
    departure: "17:35",
  },
  {
    trainNo: "12786",
    trainName: "Mysuru - Kacheguda SF Express",
    status: "Passing Through",
    arrival: "17:45",
    departure: "18:00",
  },
  {
    trainNo: "16535",
    trainName: "Mysuru - Solapur Gol Gumbaz",
    status: "Passing Through",
    arrival: "18:25",
    departure: "18:35",
  },
  {
    trainNo: "22688",
    trainName: "Varanasi - Mysuru SF Express",
    status: "Passing Through",
    arrival: "18:25",
    departure: "18:30",
  },
  {
    trainNo: "06552",
    trainName: "Jolarpettai - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "18:45",
    departure: "--",
  },
  {
    trainNo: "16232",
    trainName: "Mysuru - Mayiladuthurai Express",
    status: "Passing Through",
    arrival: "18:50",
    departure: "19:00",
  },
  {
    trainNo: "12678",
    trainName: "Ernakulam - KSR Bengaluru InterCity",
    status: "Terminating",
    arrival: "19:50",
    departure: "--",
  },
  {
    trainNo: "20662",
    trainName: "Dharwad - KSR Bengaluru Vande Bharat",
    status: "Terminating",
    arrival: "19:45",
    departure: "--",
  },
  {
    trainNo: "16526",
    trainName: "KSR Bengaluru - Kanyakumari Island",
    status: "Originating",
    arrival: "--",
    departure: "20:00",
  },
  {
    trainNo: "16585",
    trainName: "SMVT Bengaluru - Murdeshwar Exp",
    status: "Passing Through",
    arrival: "20:15",
    departure: "20:25",
  },
  {
    trainNo: "11302",
    trainName: "KSR Bengaluru - Mumbai Udyan Exp",
    status: "Originating",
    arrival: "--",
    departure: "20:45",
  },
  {
    trainNo: "66539",
    trainName: "Jolarpettai - KSR Bengaluru MEMU",
    status: "Terminating",
    arrival: "21:05",
    departure: "--",
  },
  {
    trainNo: "12080",
    trainName: "Hubballi - KSR Bengaluru Jan Shatabdi",
    status: "Terminating",
    arrival: "21:15",
    departure: "--",
  },
  {
    trainNo: "11013",
    trainName: "Mumbai LTT - Coimbatore Express",
    status: "Passing Through",
    arrival: "21:15",
    departure: "21:50",
  }
]